# Generated by Django 3.2.5 on 2024-08-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='date_of_admission',
            new_name='date_of_joining',
        ),
    ]
