# Generated by Django 6.1 on 2026-09-01 14:16

import apps.staffs.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0008_feecategory_holiday_schooldetail_and_more"),
        ("staffs", "0004_staff_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffBulkUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now=True)),
                (
                    "csv_file",
                    models.FileField(
                        upload_to="staff/bulkupload/",
                        validators=[apps.staffs.models.validate_file_extension],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Category Name")),
            ],
            options={
                "verbose_name": "StaffCategory",
                "verbose_name_plural": "StaffCategorys",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="adhar_card_number",
            field=models.CharField(
                blank=True,
                help_text="Enter 12digit adharcard number.",
                max_length=12,
                null=True,
                verbose_name="Adharcard Number",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="class_incharge",
            field=models.ForeignKey(
                blank=True,
                help_text="If staff is a class incharge of any class, select a class.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corecode.studentclass",
                verbose_name="Class Incharge",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="emp_code",
            field=models.CharField(
                default="VAMS/emp/2026/0901141517", max_length=200, unique=True
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="pancard_number",
            field=models.CharField(
                blank=True,
                help_text="Enter PAN Card number.",
                max_length=12,
                null=True,
                verbose_name="Pancard Number",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="staffs/profile_image/",
                verbose_name="Staff Image",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="subject_expert",
            field=models.ManyToManyField(
                help_text="Select as many subjects which can be taught by this staff.",
                to="corecode.subject",
                verbose_name="Subjects",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="current_status",
            field=models.BooleanField(
                choices=[(1, "Active"), (0, "Inactive")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="firstname",
            field=models.CharField(max_length=200, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the phone number without prefix. e.g. +91 or 0",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="other_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="surname",
            field=models.CharField(max_length=200, verbose_name="Last Name"),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select Staff Category e.g. Teaching Staff, Helping Staff",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staffs.staffcategory",
                verbose_name="Staff Category",
            ),
        ),
        migrations.CreateModel(
            name="StaffDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="staff_documents/")),
                ("title", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="staffs.staff",
                    ),
                ),
            ],
        ),
    ]
