# Generated by Django 6.1 on 2026-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0005_staffbulkupload_staffcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="emp_code",
            field=models.CharField(
                default="VAMS/emp/2026/0901142612", max_length=200, unique=True
            ),
        ),
    ]
