# Generated by Django 3.2.5 on 2024-08-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20240807_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=50, null=True, verbose_name='Month'),
        ),
    ]
