# Generated by Django 3.2.5 on 2024-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_invoice_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='balance_from_previous_term',
            new_name='previous_balance',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True, verbose_name='Month'),
        ),
    ]
