# Generated by Django 3.2.5 on 2024-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20240807_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
