# Generated by Django 3.2.5 on 2024-08-08 12:21

import apps.finance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_auto_20240807_1250'),
        ('finance', '0007_alter_invoice_previous_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='August', max_length=50, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(blank=True, default=apps.finance.models.get_current_academic_session, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.academicsession'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(blank=True, default=apps.finance.models.get_current_academic_term, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.academicterm'),
        ),
    ]
