# Generated by Django 4.2.15 on 2025-02-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_alter_invoice_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="February",
                max_length=50,
                null=True,
                verbose_name="Month",
            ),
        ),
    ]
