# Generated by Django 4.2.15 on 2025-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_invoiceitem_payment_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="payment_mode",
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("cash", "Cash"),
                    ("debit-card", "Debit Card"),
                    ("credit-card", "Credit Card"),
                    ("net-banking", "Net Banking"),
                    ("select", "Select"),
                ],
                default="select",
                max_length=50,
            ),
        ),
    ]
