# Generated by Django 6.1 on 2026-09-01 14:16

import apps.finance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_remove_invoiceitem_payment_mode_receipt_payment_mode"),
        ("students", "0022_alter_student_registration_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceBulkUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now=True)),
                ("csv_file", models.FileField(upload_to="invoice/bulkupload/")),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_payable",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default=apps.finance.models.Invoice.get_current_month,
                max_length=50,
                null=True,
                verbose_name="Month",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Closed")], default=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_items",
                to="finance.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="finance.invoice",
            ),
        ),
        migrations.CreateModel(
            name="Concession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concession_type",
                    models.CharField(
                        choices=[
                            ("rte", "RTE"),
                            ("sibling", "Sibling"),
                            ("staff_ward", "Staff Ward"),
                            ("merit", "Merit Scholarship"),
                            ("govt_scholarship", "Govt. Scholarship"),
                            ("ews", "EWS"),
                            ("differently_abled", "Differently Abled"),
                            ("discretionary", "Management Discretionary"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concessions",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
