# Generated by Django 6.1 on 2026-09-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corecode", "0008_feecategory_holiday_schooldetail_and_more"),
        ("students", "0024_alter_student_registration_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAssignmentNProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        help_text="Upload only .pdf, .txt, .docx, .jpg or .jpeg file only",
                        upload_to="assignments/",
                        verbose_name="Upload File",
                    ),
                ),
                (
                    "is_assignment_for_all",
                    models.BooleanField(
                        default=True,
                        help_text="If assignment/project is for all students of selected class.",
                        verbose_name="All Students",
                    ),
                ),
                ("due_date", models.DateField(auto_now=True, verbose_name="Due Date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "for_class",
                    models.ForeignKey(
                        help_text="Upload file of maxsize upto 10MBs only.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corecode.studentclass",
                        verbose_name="Class",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        null=True, to="students.student", verbose_name="Students"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "ClassAssignmentNProject",
                "verbose_name_plural": "ClassAssignmentNProjects",
            },
        ),
        migrations.CreateModel(
            name="StudentAssignmentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_submitted", models.BooleanField(default=False)),
                (
                    "submitted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="assignments/submissions/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="project_n_assignments.classassignmentnproject",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Assignment Status",
                "verbose_name_plural": "Student Assignment Statuses",
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
