# Generated by Django 5.1 on 2024-08-14 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_student_user_alter_student_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="adharcard_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered Adhar number isn't valid!",
                        regex="^[0-9]{12,12}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                default="Vedika/2024/0814202707", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="surname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
