# Generated by Django 4.2.15 on 2024-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_student_adharcard_number_student_father_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                default="Vedika/2024/0901154436", max_length=200, unique=True
            ),
        ),
    ]
