# Generated by Django 4.2.15 on 2025-02-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_alter_student_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                default="Vedika/2025/0218200328", max_length=200, unique=True
            ),
        ),
    ]
