# Generated by Django 4.2.15 on 2025-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0021_alter_student_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                default="Vedika/2025/0218200826", max_length=200, unique=True
            ),
        ),
    ]
