# Generated by Django 6.1 on 2026-09-01 14:16

import apps.students.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0008_feecategory_holiday_schooldetail_and_more"),
        ("students", "0022_alter_student_registration_number"),
        ("transport", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasteCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Caste")),
            ],
            options={
                "verbose_name": "CasteCategory",
                "verbose_name_plural": "CasteCategorys",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Category")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categorys",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["surname", "firstname", "other_name"],
                "permissions": [
                    ("can_promote_students", "Can promote students to next class")
                ],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="drop_time",
            field=models.TimeField(
                blank=True, help_text="Drop time for the student", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact_number",
            field=models.CharField(
                blank=True,
                help_text="Enter emergency contact number",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Contact No.",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="fee_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corecode.feecategory",
                verbose_name="Fee Category",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="last_class_attended",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_class",
                to="corecode.studentclass",
                verbose_name="Last Class Attended",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="medium_of_instruction",
            field=models.CharField(
                choices=[(0, "English"), (0, "Hindi")],
                default=0,
                max_length=50,
                verbose_name="Medium",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="name_of_previous_school",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Name of Previous School",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="number_of_siblings",
            field=models.IntegerField(
                default=0,
                help_text="Number of siblings studying in this school (including this student)",
                verbose_name="Number of Siblings",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pen_number",
            field=models.CharField(
                blank=True,
                help_text="Please enter PEN number",
                max_length=100,
                null=True,
                verbose_name="PEN Number",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pickup_drop_location",
            field=models.CharField(
                blank=True,
                help_text="Pickup/Drop location for transport",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pickup_time",
            field=models.TimeField(
                blank=True, help_text="Pickup time for the student", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="reason_of_leaving",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reason of Leaving"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="relation_with_student",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Relation with student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Roll Number"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="transport.route",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="select_siblings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Press Hold down “Control”, or “Command” on a Mac, to select more than one.",
                null=True,
                to="students.student",
                verbose_name="Select Siblings",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="sr_number",
            field=models.CharField(
                blank=True,
                help_text="Please enter SR number",
                max_length=100,
                null=True,
                verbose_name="SR Number",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students/profile_image/",
                verbose_name="Student Image",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="student",
            name="uses_transport",
            field=models.BooleanField(
                default=False,
                help_text="Does the student use school transport?",
                verbose_name="School Transport",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="adharcard",
            field=models.ImageField(
                blank=True,
                help_text="Upload adharcard Image",
                upload_to="students/adharcard/",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="adharcard_number",
            field=models.CharField(
                blank=True,
                help_text="Enter 12 digit adharcard number",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered Adhar number isn't valid!",
                        regex="^[0-9]{12,12}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.studentclass",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="current_status",
            field=models.BooleanField(
                choices=[(1, "Active"), (0, "Inactive")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Father's Name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="firstname",
            field=models.CharField(max_length=200, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Mother's Name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="other_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Enter parent's mobile number.",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Contact No.",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                help_text="VAMS/2026/09/01/17", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="surname",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="studentbulkupload",
            name="csv_file",
            field=models.FileField(
                upload_to="students/bulkupload/",
                validators=[apps.students.models.validate_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="caste_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.castecategory",
                verbose_name="Caste",
            ),
        ),
        migrations.AddField(
            model_name="castecategory",
            name="parent_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.category",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.category",
                verbose_name="Category",
            ),
        ),
    ]
