# Generated by Django 6.1 on 2026-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0023_castecategory_category_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                help_text="VAMS/2026/09/01/40", max_length=200, unique=True
            ),
        ),
    ]
