# Generated by Django 6.1 on 2026-09-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "driver_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="transport/driver/"
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "upload_dl",
                    models.ImageField(
                        blank=True, null=True, upload_to="transport/driver/dl/"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_location", models.CharField(max_length=100)),
                ("end_location", models.CharField(max_length=100)),
                (
                    "stops",
                    models.TextField(
                        help_text="Enter stop locations separated by commas"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("bus", "Bus"), ("van", "Van"), ("car", "Car")],
                        max_length=10,
                    ),
                ),
                (
                    "vehicle_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="transport/vehicle/"
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transport.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_time", models.TimeField()),
                ("drop_time", models.TimeField()),
                (
                    "days_operating",
                    models.CharField(help_text="E.g., Monday-Friday", max_length=100),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.vehicle",
                    ),
                ),
            ],
        ),
    ]
