# Generated by Django 3.2.5 on 2024-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='admission_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='computer_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='exam_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='miscellaneous',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='tuition_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
