# Generated by Django 3.2.5 on 2024-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_auto_20240807_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_max_marks',
            field=models.IntegerField(default=100, verbose_name='Exam Maximum Marks'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test_max_marks',
            field=models.IntegerField(default=50, verbose_name='Test Maximum Marks'),
        ),
    ]
