# Generated by Django 5.1 on 2024-08-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0006_auto_20240807_1250"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageImageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_5",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_6",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_7",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_8",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_9",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_10",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_11",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_12",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_13",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_14",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_15",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_16",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_17",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_18",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_19",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
                (
                    "image_20",
                    models.ImageField(blank=True, null=True, upload_to="email/images/"),
                ),
            ],
            options={
                "verbose_name": "EmailMessageImageLink",
                "verbose_name_plural": "EmailMessageImageLinks",
            },
        ),
    ]
