# Generated by Django 6.1 on 2026-09-01 14:16

import apps.corecode.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0007_emailmessageimagelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "is_rte",
                    models.BooleanField(
                        default=False,
                        help_text="Students in this category are never charged tuition fees.",
                        verbose_name="RTE (Right to Education)",
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "FeeCategory",
                "verbose_name_plural": "FeeCategories",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="My School",
                        max_length=255,
                        unique=True,
                        verbose_name="School Name",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="VAMS",
                        max_length=50,
                        unique=True,
                        verbose_name="School Short Name",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="School Slogan",
                    ),
                ),
                ("address", models.TextField(verbose_name="School Address")),
                (
                    "fee_collection",
                    models.IntegerField(
                        choices=[
                            (0, "Monthly"),
                            (1, "Quaterly"),
                            (2, "Half Yearly"),
                            (3, "Yearly"),
                        ],
                        default=0,
                        verbose_name="Fee Collection Type",
                    ),
                ),
                (
                    "logo_vertical",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png")
                            ),
                            apps.corecode.models.validate_file_size,
                        ],
                        verbose_name="Vertical Logo",
                    ),
                ),
                (
                    "logo_horizontal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png")
                            ),
                            apps.corecode.models.validate_file_size,
                        ],
                        verbose_name="Horizontal Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school/favicon/",
                        validators=[
                            django.core.validators.FileExtensionValidator(("ico",)),
                            apps.corecode.models.validate_file_size,
                        ],
                        verbose_name="Favicon Icon",
                    ),
                ),
                (
                    "letterhead",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school/letterhead/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png")
                            ),
                            apps.corecode.models.validate_file_size,
                        ],
                        verbose_name="Letterhead Image",
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school/signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png")
                            ),
                            apps.corecode.models.validate_file_size,
                        ],
                        verbose_name="Signature Image",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school/backgrounds/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png")
                            ),
                            apps.corecode.models.validate_file_size,
                        ],
                        verbose_name="First Page Background",
                    ),
                ),
                (
                    "authorized_signatory",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Authorized Signatory",
                    ),
                ),
                (
                    "school_strength",
                    models.PositiveIntegerField(
                        default=0, verbose_name="School Strength"
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        choices=[("English", "English"), ("Hindi", "Hindi")],
                        max_length=10,
                        verbose_name="Medium of Instruction",
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="School Subdomain"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SchoolDetail",
                "verbose_name_plural": "SchoolDetails",
            },
        ),
        migrations.AddField(
            model_name="academicsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicsession",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="End Date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicsession",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Start Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="academicterm",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicterm",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="End Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicterm",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Start Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicterm",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="admission_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="computer_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="exam_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="miscellaneous",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="tuition_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="ClassSubjectRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corecode.studentclass",
                        verbose_name="Class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="corecode.subject",
                        verbose_name="Subjects",
                    ),
                ),
            ],
            options={
                "verbose_name": "ClassSubjectRelation",
                "verbose_name_plural": "ClassSubjectRelations",
            },
        ),
    ]
