# Generated by Django 3.2.5 on 2024-08-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0013_alter_student_registration_number'),
        ('staffs', '0003_rename_date_of_admission_staff_date_of_joining'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('on-leave', 'On-leave'), ('other', 'Other')], max_length=50, null=True, verbose_name='Status')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Name')),
            ],
            options={
                'verbose_name': 'StudentAttendance',
                'verbose_name_plural': 'StudentAttendances',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('on-leave', 'On-leave'), ('other', 'Other')], max_length=50, null=True, verbose_name='Status')),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='Time-In')),
                ('time_out', models.DateTimeField(auto_now=True, verbose_name='Time-Out')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff', verbose_name='Staff Name')),
            ],
            options={
                'verbose_name': 'StaffAttendance',
                'verbose_name_plural': 'StaffAttendances',
            },
        ),
    ]
