# Generated by Django 6.1 on 2026-09-01 14:16

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_auto_20240808_1257"),
        ("staffs", "0005_staffbulkupload_staffcategory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffattendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated_at"),
        ),
        migrations.AlterField(
            model_name="staffattendance",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Present"), (0, "Absent"), (2, "On-leave"), (3, "Other")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="staffattendance",
            name="time_in",
            field=models.TimeField(blank=True, null=True, verbose_name="Time-In"),
        ),
        migrations.AlterField(
            model_name="staffattendance",
            name="time_out",
            field=models.TimeField(blank=True, null=True, verbose_name="Time-Out"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Present"), (0, "Absent"), (2, "On-leave"), (3, "Other")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="StaffLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Approved"), (2, "Rejected")],
                        default=0,
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_request",
                        to="staffs.staff",
                        verbose_name="Staff Name",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "StaffLeaveRequest",
                "verbose_name_plural": "StaffLeaveRequests",
            },
        ),
    ]
